### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Yaswanthroy** [friendly-telegram/modules-repo#1]
Can u add permission to allow PM's otherwise auto report spam automatically

**Comment by iamd7h** [comment]
@Yaswanthroy Yeah it is there iirc

**Comment by AvinashReddy3108** [comment]
> Can u add permission to allow PM's otherwise auto report spam automatically

The [NO PMs](https://github.com/friendly-telegram/modules-repo/blob/master/nopm.py) module is exactly what you need.
