### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by penn5** [friendly-telegram/modules-repo#2]
Add things you want. I might add them

**Comment by androidacy-user** [comment]
@penn5 More group admin commands

Eg .un/ban, .un/mute, .pin, etc

**Comment by penn5** [comment]
@alexa-v2 working on that literally rn

**Comment by androidacy-user** [comment]
@penn5 Cool doing great 👍

**Comment by pqhaa** [comment]
@penn5 Add custom language support for .tts

Ex: .tts ru <text> will process text in Russian rather than English.
Or .tts ru | <text> maybe

**Comment by penn5** [comment]
@pqhaa Can you detail the syntax? I would like to have a way to default to English, but I couldn't think of a good syntax that would work for this.

**Comment by pqhaa** [comment]
@penn5 Maybe 
Syntax: no reply:
.tts <lang> | <text>
Example:
.tts ru | Привет!
Will say Hi in Russian

Syntax: reply:
.tts <lang>
Example:
* Reply to text, msg: Привет! *
.tts ru
Will reply to the text with audio saying Hi

But if user is replying to a text with
.tts ru | Привет! 
It'll say Hi instead of saying the replying to msg text.

**Comment by penn5** [comment]
@pqhaa Sounds good, I'll code this in Geography. cc @YukiSuter

**Comment by pqhaa** [comment]
@penn5 Okay, thanks! :D

**Comment by AvinashReddy3108** [comment]
> @pqhaa Sounds good, I'll code this in Geography. cc @YukiSuter

Do add verification of language codes too, `gTTS` and `GoogleTranslate` does not take some language codes.

**Comment by penn5** [comment]
@AvinashReddy3108 It would surely throw an error if language code is incorrect, just need to catch it

**Comment by pqhaa** [comment]
@penn5 Some more requests:
1. Command aliases
For .translate - .trt (or .tr)
For .terminal - .term
Etc
2. Urban dictionary command
Usage:
.urban <word> 
Will edit the msg to word and definition
Probable alias: .ud

**Comment by penn5** [comment]
@pqhaa aliases is an awesome idea!

**Comment by pqhaa** [comment]
@penn5 Maybe just allow users to add them and store in the cloud, but may be a little bit hard, idk

**Comment by YukiSuter** [comment]
Bro it's Ur birthday why are u still working on this 😂😂

**Comment by penn5** [comment]
@YukiSuter its not my birthday.also stop leaking personal info publicly

**Comment by YukiSuter** [comment]
Oh rip I forgot this is a GitHub email

**Comment by penn5** [comment]
@pqhaa Aliases done

**Comment by pqhaa** [comment]
@penn5 Nice, good job!

**Comment by ghost** [comment]
@penn5 Great 👌

**Comment by czwhynot1** [comment]
> @penn5 More group admin commands
> 
> Eg .un/ban, .un/mute, .pin, etc

+1

**Comment by davinash97** [comment]
G-Drive sar

**Comment by penn5** [comment]
> G-Drive sar

I don't like google drive, because its a proprietary service and there are better alternatives, also tg intergration doesnt help anyone

**Comment by penn5** [comment]
> @penn5 Some more requests:
> 
> 1. Command aliases
>    For .translate - .trt (or .tr)
>    For .terminal - .term
>    Etc
> 2. Urban dictionary command
>    Usage:
>    .urban 
>    Will edit the msg to word and definition
>    Probable alias: .ud

@AvinashReddy3108 wanna try?

**Comment by loque036** [comment]
a user suggested to add a welcome module so ig this goes in here

**Comment by penn5** [comment]
@loque036 @AvinashReddy3108

**Comment by AvinashReddy3108** [comment]
@loque036 Hmm, that would not be good. Coz if the welcome module is activated in too many groups, a floodwait may occur which may affect the user's ability to interact with Telegram's service in more ways than one.

**Comment by loque036** [comment]
@AvinashReddy3108 as i said, another guy requested it, not me. also uniborg has it afaik. again, it would be optional to turn on or off i suppose

**Comment by penn5** [comment]
@loque036 It seems like a valid suggestion. But it should be off by default.

**Comment by overclockedboi** [comment]
PM_AUTO_BAN

**Comment by overclockedboi** [comment]
PM_AUTO_BAN please 😁

**Comment by Lucky056** [comment]
.leave command to leave groups or chats. Also a bot log chat group like ppe has which displays all the tasks the userbot performs successfully or if bot crashes it pastes the error logs directly. Using the botchat id.

**Comment by OnePerson10** [comment]
.profilepic command for change the profile pic
.bio command for change the biography
.username command for change the username

**Comment by AvinashReddy3108** [comment]
> .profilepic command for change the profile pic
> .bio command for change the biography
> .username command for change the username

Really, are we humans that lazy ? :thinking:

**Comment by sreeharimkl** [comment]
Pls add magisk,twrp, etc😁
That's like the android module in ppe

**Comment by loque036** [comment]
@sreeharimkl I said this yesterday and i will keep saying it. You can load modules from paperplane / uniborg based bots. There is a compatibility layer and it's there for something.

**Comment by ghost** [comment]
@sreeharimkl U can install android.py from raphi or ppe to get that thing

**Comment by sreeharimkl** [comment]
> @sreeharimkl I said this yesterday and i will keep saying it. You can load modules from paperplane / uniborg based bots. There is a compatibility layer and it's there for something.

After a restart the loaded plugins will disappear..

**Comment by sreeharimkl** [comment]
> @sreeharimkl U can install android.py from raphi or ppe to get that thing

I know that.. It's feature request right?! I requested it to be default in ftg😴

**Comment by loque036** [comment]
@sreeharimkl #worksfineoverhere, might be a heroku issue as most of you host the bot there. I have a raspberry pi so it doesn't happen to me, and If i can recall correctly the issue was fixed already.

**Comment by penn5** [comment]
@sreeharimkl No.

**Comment by androidacy-user** [comment]
> @sreeharimkl #worksfineoverhere, might be a heroku issue as most of you host the bot there. I have a raspberry pi so it doesn't happen to me, and If i can recall correctly the issue was fixed already.

@loque036 same issue, plug-ins disappear after restart or update. Hosting directly on a dedicated server

**Comment by androidacy-user** [comment]
@loque036 BTW you do realize PaperplaneExtended, like any bots based on paper plane, are essentially dead? Development has stopped due to some sort of licensing issue

**Comment by penn5** [comment]
Closing in favour of https://github.com/friendly-telegram/friendly-telegram/issues/46

**Comment by ghost** [comment]
Saving and retrieving notes
