### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by kenny2281337** [friendly-telegram/modules-repo#38]
![Screenshot_20200206-234610](https://user-images.githubusercontent.com/48866699/73980786-0512aa80-4942-11ea-82f4-26f9fd551cb2.png)
![Uploading Screenshot_20200206-225918.png…]()

**Comment by kenny2281337** [comment]
![Screenshot_20200206-225918](https://user-images.githubusercontent.com/48866699/73980824-122f9980-4942-11ea-9b03-ba35021d60c7.png)

**Comment by penn5** [comment]
This is user error.
