### ISSUE TITLE
Some feature request 

### ISSUE THREAD

**Issue by Yaswanthroy** [friendly-telegram/modules-repo#4]
1)Can u add .filter in groups and personal chats it will be very useful bro 
2)And can u add translation from uniborg or PPE
3)AUTO_PM_BAN it must for many users bro please try to implement that too
4)import memes modules from PPE bro they are cool 
5)instead of manually unafk can u automatically unafk when i send a msg in groups  same like PPE
6)Add some admin commands

**Comment by ghost** [comment]
@Yaswanthroy +69 those implementations would be great , specially that automatic unafk

**Comment by loque036** [comment]
@Yaswanthroy point 2 and 4 you can do them already, that's why the compatibility layer exists and the modules that you load with .dlmod <raw_module_url> stay loaded for ever unless you manually unload them

**Comment by AvinashReddy3108** [comment]
> @Yaswanthroy point 2 and 4 you can do them already, that's why the compatibility layer exists and the modules that you load with .dlmod <raw_module_url> stay loaded for ever unless you manually unload them

Yeah, but I'll try to bring this up as a native module in FTG.

**Comment by penn5** [comment]
@AvinashReddy3108 awesome thanks

**Comment by penn5** [comment]
Closing in favour of https://github.com/friendly-telegram/friendly-telegram/issues/46
