### ISSUE TITLE
Alternative upload sites

### ISSUE THREAD

**Issue by ghost** [friendly-telegram/modules-repo#5]
https://transfer.zonari.us/

https://www.filesend.jp/l/en-US/

https://bitsend.jp/?setLang=en

 upload sites like these offer us more quota than transfersh, please consider

**Comment by rsoorajs** [comment]
yes..please consider these sites !
+

https://cowtransfer.com
https://bashupload.com

**Comment by penn5** [comment]
I'm accepting PRs, it should be fairly simple.

**Comment by penn5** [comment]
transfer.zonari.us 404's on the homepage.
filesend.jp doesn't have a (publicly documented) API
bitsend.jp looks *very* dodgy, i.e. Lorem ipsum in the FAQ, also no API
cowtransfer.com: I can't find an API, and it had a "PRO" version so it probably doesn't have one
bashupload.com is already supported: just set the UPLOAD_URL to `https://bashupload.com/{}`
